version: '3.3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: postgres
    env_file:
      - .env
    ports:
      - '15432:5432'
volumes:
  db:
    driver: local
